name: test
# Runs the Devbox installer tests

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  push:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install devbox
        uses: ./
        with:
          project-path: 'testdata'

  test-action-with-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install devbox
        uses: ./
        with:
          devbox-version: '0.2.0'
          project-path: 'testdata'

  test-action-with-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install devbox
        uses: ./
        with:
          enable-cache: true
          project-path: 'testdata'
